name: stylit
description: "A Flutter package that allows you to effortlessly turn a plain string into a beautifully styled Text widget."
version: 0.0.2
homepage: https://github.com/GeekAbdelouahed/stylit

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: